(define-module (demo enemies)
  #:use-module (oop goops)
  #:use-module (gnumaku generics)
  #:use-module (gnumaku core)
  #:use-module (gnumaku actor)
  #:use-module (gnumaku enemy)
  #:use-module (gnumaku primitives)
  #:use-module (gnumaku coroutine)
  #:export (make-enemy-1))

(define (make-enemy-1 x y image)
  (let ((enemy (make <enemy> #:sprite (make-sprite image) #:health 50 #:points 100)))
    (set-position enemy x y)
    (center-sprite-image! (sprite enemy))
    (coroutine
     (wait enemy 1)
     (let loop ((rotate 0))
       (let ((x (get-x enemy))
             (y (get-y enemy))
             (system (bullet-system enemy)))
         (emit-circle system x y 32 16 rotate 50 5 5 'medium-blue)
         ;; (emit-circle system x y 32 16 (+ rotate 4) 50 5 5 'small-diamond)
         (wait enemy 15)
         (loop (+ rotate 10)))))
    enemy))
