(define-module (demo enemies)
  #:use-module (oop goops)
  #:use-module (gnumaku generics)
  #:use-module (gnumaku core)
  #:use-module (gnumaku actor)
  #:use-module (gnumaku enemy)
  #:use-module (gnumaku primitives)
  #:use-module (gnumaku coroutine)
  #:use-module (demo patterns)
  #:export (make-enemy-1))

(define (make-enemy-1 x y image)
  (let ((enemy (make <enemy> #:sprite (make-sprite image) #:health 50 #:points 100)))
    (set-position enemy x y)
    (center-sprite-image! (sprite enemy))
    (test-pattern-1 enemy)
    enemy))
